name: build_test_lint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run test:coverage:threshold
      - run: npm run lint
      - run: npm run api:check
