# Description: This workflow mimic the flow of behaviors when user using Amplify CLI;

name: 'poc-e2e-flow-test'

on:
  push:
    branches:
      - poc/e2e-test

jobs:
  create-amplify-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [18]
        pkg-manager: [npm, yarn1, yarn3, pnpm, bun]
        exclude:
          - os: windows-latest
            pkg-manager: bun # bun only have limit support on windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout aws-amplify/amplify-cli repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1. TODO: try only fetch .github/workflow
      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 #4.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: ${{matrix.pkg-manager}}-create-amplify-project
        if: matrix.pkg-manager != 'yarn1' && matrix.pkg-manager != 'yarn3'
        shell: bash
        run: |
          mkdir -p /tmp/amplify-project; cd /tmp/amplify-project
          npm install -g ${{matrix.pkg-manager}}
          ${{matrix.pkg-manager}} create amplify@alpha --yes
      - name: ${{matrix.pkg-manager}}-create-amplify-project-step1-install
        continue-on-error: true
        if: matrix.pkg-manager == 'yarn1'
        shell: bash
        run: | # yarn1 create amplify doesn't work with @ahpha tag
          mkdir -p /tmp/amplify-project; cd /tmp/amplify-project
          echo "yarn version: $(yarn --version)"
          yarn create amplify@alpha
      - name: ${{matrix.pkg-manager}}-create-amplify-project-step2-setup-not-win
        if: ${{matrix.pkg-manager == 'yarn1' && matrix.os != 'windows-latest'}}
        shell: bash
        run: |
          /usr/local/bin/create-amplify
      - name: ${{matrix.pkg-manager}}-create-amplify-project-step2-setup-win
        if: ${{matrix.pkg-manager == 'yarn1' && matrix.os == 'windows-latest'}}
        shell: bash
        run: |
          C:\npm\prefix\bin\create-amplify
