# Description: This workflow mimic the flow of behaviors when user using Amplify CLI;

name: 'poc-e2e-flow-test'

on: # TODO: need to change the trigger
  push:
    branches:
      - poc/e2e-test

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # version 3.6.0
      - uses: ./.github/actions/setup_node
      - uses: ./.github/actions/install_with_cache
  build:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # version 3.6.0
      - uses: ./.github/actions/setup_node
      - uses: ./.github/actions/build_with_cache
  run_e2e_tests:
    strategy:
      # will finish running other test matrices even if one fails
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    needs:
      - build
    permissions:
      # these permissions are required for the configure-aws-credentials action to get a JWT from GitHub
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # version 3.6.0
      - uses: ./.github/actions/setup_node
      - uses: ./.github/actions/restore_build_cache
      - run: cd packages/cli && npm link
      - name: Run E2E tests
        run: npm run test:dir packages/integration-tests/src/test-e2e/create_amplify.test.ts

      # - name: yarn-stable-create-amplify-project
      #   if: matrix.pkg-manager == 'yarn-stable'
      #   shell: bash
      #   run: |
      #     mkdir -p /tmp/amplify-project; cd /tmp/amplify-project
      #     corepack enable
      #     echo "yarn set version stable"
      #     yarn set version stable
      #     echo "yarn version $(yarn --version)"
      #     yarn config set unsafeHttpWhitelist localhost
      #     yarn config set npmRegistryServer http://localhost:4873
      #     PACKAGE_MANAGER_EXECUTABLE=yarn npm run test:dir packages/integration-tests/src/test-e2e/create_amplify.test.ts
