# Description: This workflow mimic the flow of behaviors when user using Amplify CLI;

name: 'poc-e2e-flow-test'

on: # TODO: need to change the trigger
  push:
    branches:
      - poc/e2e-test

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout aws-amplify/amplify-cli repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Node.js
        uses: ./.github/actions/setup_node
      - name: Install or Restore Cache
        uses: ./.github/actions/install_with_cache
  build:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - name: Checkout aws-amplify/amplify-cli repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Node.js
        uses: ./.github/actions/setup_node
      - name: Build or Restore Build Cache
        uses: ./.github/actions/build_with_cache
  run_e2e_tests:
    strategy:
      # will finish running other test matrices even if one fails
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pkg-manager: [npm, yarn, yarn-stable, pnpm]
    env:
      ACKAGE_MANAGER_EXECUTABLE: ${{ matrix.pkg-manager }} # TODO: remove PACKAGE_MANAGER_EXECUTABLE once CLI is able to getPackageManager().
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    needs:
      - build
    permissions:
      # these permissions are required for the configure-aws-credentials action to get a JWT from GitHub
      id-token: write
      contents: read
    steps:
      - name: Checkout aws-amplify/amplify-cli repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Node.js
        uses: ./.github/actions/setup_node
      - name: Restore Build Cache
        uses: ./.github/actions/restore_build_cache
      - name: Run E2E tests with ${{ matrix.pkg-manager }}
        if: matrix.pkg-manager != 'yarn-stable'
        run: |
          npm install -g ${{matrix.pkg-manager}}
          echo "$(${{matrix.pkg-manager}}) config set registry http://localhost:4873"
          ${{matrix.pkg-manager}} config set registry http://localhost:4873
          echo "$(${{matrix.pkg-manager}}) config get registry"
          ${{matrix.pkg-manager}} config get registry
          npm run test:dir packages/integration-tests/src/test-e2e/create_amplify.test.ts
      - name: Run E2E tests with Yarn Stable
        if: matrix.pkg-manager == 'yarn-stable'
        shell: bash
        run: |
          corepack enable
          echo "yarn set version stable"
          yarn set version stable
          echo "git commit -am 'chore: update yarn version to stable'"
          git commit -am "chore: update yarn version to stable"
          echo "yarn version $(yarn --version)"
          yarn config set unsafeHttpWhitelist localhost
          yarn config set npmRegistryServer http://localhost:4873
          PACKAGE_MANAGER_EXECUTABLE=yarn npm run test:dir packages/integration-tests/src/test-e2e/create_amplify.test.ts
